### ISSUE TITLE
Update iOS Google Mobile Ads SDK

### ISSUE THREAD

**Issue by emiliobongiorno** [xamarin/GoogleApisForiOSComponents#309]
Currently the version of the Google Mobile Ads SDK used by Xamarin.Google.iOS.MobileAds is 7.38.0
The latest version is 7.50.0 and has several important updates.

**I am having issues showing interstitial ads on iOS13**. They are shown as modals (this new 'popups' of iOS 13), and I want to show them on full screen as before.
I used [this implementation for iOS Intesrtitials](https://www.c-sharpcorner.com/article/google-admob-display-ads-in-xamarin-forms/) (look for AdInterstitial_iOS class)
I already tried to do something like this but still showing as popups on iOS13:
`viewController.ModalPresentationStyle = UIModalPresentationStyle.FullScreen;
`
I read that the default for iOS 13 is to show them as modal, and that could be the reason why I can't force the interstitial to be shown on full screen.
Am I missing something or there should be an update on this library for fixing that?

**Comment by tipa** [comment]
The Nuget package apparent got updated to v7.47.0, however my apps now fail to compile:
![image](https://user-images.githubusercontent.com/2863198/66253322-dc499100-e766-11e9-9b1d-1b0f00e5fe4e.png)

**Comment by SotoiGhost** [comment]
@emiliobongiorno An update for Google Mobile Ads has been pushed, please, try updating to see if the update fixes the problem.

@tipa That error seems to happen when Xamarin.Build.Download NuGet was not restored correctly or there was a problem when downloading the Framework. Please, delete the [Xamarin.Build.Download cache][1], bin and obj folders, restore again the NuGets on the solution and try again.

[1]: https://github.com/xamarin/XamarinComponents/blob/master/Util/Xamarin.Build.Download/source/Xamarin.Build.Download/Xamarin.Build.Download.props#L8-L9

**Comment by emiliobongiorno** [comment]
It is fixed now! 
The ads are shown in full screen.
Thanks @SotoiGhost

**Comment by SotoiGhost** [comment]
@emiliobongiorno Glad to know that it's working! Closing this issue now! Best!

**Comment by tipa** [comment]
@SotoiGhost did what you told me (on both PC and Mac) but the error still showed up. Recognized that the XamarinBuildCache folder wasn't recreated so I manually added the Xamarin.Build.Download Nuget package to my project and it then started working. Maybe the library is missing a dependency reference?

**Comment by SotoiGhost** [comment]
@tipa Are you using Firebase somehow?

**Comment by tipa** [comment]
No I am not. I was only able to resolve the problem by manually adding those two Nuget dependencies to my project:
`Xamarin.Firebase.iOS.Core`
`Xamarin.Build.Download`
I see that these dependencies are already required by Xamarin.Google.iOS.MobileAds but for some reason they weren't pulled in correctly. I don't know if this is a problem of Nuget, this library or Xamarin, but from a developer perspective I shouldn't have to manually add those dependencies

**Comment by SotoiGhost** [comment]
The `Xamarin.Firebase.iOS.Core` NuGet is a new dependency for it, but `Xamarin.Build.Download` package has been a dependency for a while. I can't really tell what happened there, but if you can reproduce a test case, would be great to open a new issue to try to fix it.

**Comment by tipa** [comment]
It's very easy to produce a test case, simply create a new Xamarin iOS App in Visual Studio, add the MobileAds Nuget package and the problem already occurs on my machine. 
Example project: [AdTest.zip](https://github.com/xamarin/GoogleApisForiOSComponents/files/3704817/AdTest.zip)

**Comment by tipa** [comment]
same error after adding this key

**Comment by MartinZikmund** [comment]
I am facing the same problem as @tipa with the latest Google Mobile Ads SDK

**Comment by SotoiGhost** [comment]
Guys, I don't know if this related but there's an [issue][1] right now with NuGet where it doesn't load the .props and .targets files of a Nuget's dependency. The workaround of this is to add NuGet's dependencies explicitly to your project.

Hope this helps.

[1]: https://github.com/NuGet/Home/issues/8694

**Comment by ibrahimtaleb11** [comment]
@tipa I have same problem write now can you help my how I fixed ?
