### ISSUE TITLE
Firebase.CloudFirestore - Missing Framework 'protobuf' Issue with latest release 1.4.2.0

### ISSUE THREAD

**Issue by ckomodromos** [xamarin/GoogleApisForiOSComponents#332]
When using the latest release (1.4.2.0) of the Firebase.CloudFirestore package, the app is not able to run and crashes on the splash screen with the following issue:

```
Launched application 'AppName’ on '???s iPad' with pid 940
dyld: dependent dylib '@rpath/protobuf.framework/protobuf' not found for '/AppName/Frameworks/FirebaseFirestore.framework/FirebaseFirestore', tried but didn't find: '/AppName/Frameworks/protobuf.framework/protobuf' '/AppName/Frameworks/FirebaseFirestore.framework/Frameworks/protobuf.framework/protobuf' '/AppName/Frameworks/protobuf.framework/protobuf' '@rpath/protobuf.framework/protobuf' '/System/Library/Frameworks/protobuf.framework/protobuf' 
Application ‘AppName’ terminated.
```

The packages for CloudFirestore 4.1.1 recently had the same issue and was resolved in this PR: https://github.com/xamarin/GoogleApisForiOSComponents/pull/323

Could we please get this resolved as downgrading is no longer an option as older releases will not build with the latest Xamarin iOS, Xcode, and VS for Mac.

Thanks

**Comment by SotoiGhost** [comment]
@ckomodromos A new version of Firebase Cloud Firestore with this fix has been released. Best!

**Comment by edooley** [comment]
@SotoiGhost I am still experiencing this on 1.4.2.1 and 1.4.2.2. I've never seen an issue like this before. The app builds and runs but immediately crashes before any application output can be logged. Even the system log on the simulator doesn't seem to pick it up. I have to package a release build, run it on my device, let it crash, then find it in my device logs. VS For Mac 8.4.7 on OSX 10.15.3. This is what I get:

    Incident Identifier: B5526F7A-ED47-4E34-B891-8F0B2B21F2C4
    CrashReporter Key:   1cd37ba6cb699f08e7a857e89a50f440b02ebeab
    Hardware Model:      iPhone11,2
    Process:             Catholify.iOS [5376]
    Path:                /private/var/containers/Bundle/Application/63F61338-338F-4A9B-89ED-B4F2066D6FF5/Catholify.iOS.app/Catholify.iOS
    Identifier:          com.igdit.catholify
    Version:             58 (22.1.0)
    Code Type:           ARM-64 (Native)
    Role:                Foreground
    Parent Process:      launchd [1]
    Coalition:           com.igdit.catholify [1481]
    
    
    Date/Time:           2020-02-28 16:24:22.8195 -0600
    Launch Time:         2020-02-28 16:24:22.7282 -0600
    OS Version:          iPhone OS 13.3.1 (17D50)
    Release Type:        User
    Baseband Version:    2.04.03
    Report Version:      104
    
    Exception Type:  EXC_CRASH (SIGABRT)
    Exception Codes: 0x0000000000000000, 0x0000000000000000
    Exception Note:  EXC_CORPSE_NOTIFY
    Termination Description: DYLD, dependent dylib '@rpath/Protobuf.framework/Protobuf' not found for '/private/var/containers/Bundle/Application/63F61338-338F-4A9B-89ED-B4F2066D6FF5/Catholify.iOS.app/Frameworks/FirebaseFirestore.framework/FirebaseFirestore', tried but didn't find: '/private/var/containers/Bundle/Application/63F61338-338F-4A9B-89ED-B4F2066D6FF5/Catholify.iOS.app/Frameworks/Protobuf.framework/Protobuf' '/private/var/containers/Bundle/Application/63F61338-338F-4A9B-89ED-B4F2066D6FF5/Catholify.iOS.app/Frameworks/FirebaseFirestore.framework/Frameworks/Protobuf.framework/Protobuf' '/private/var/containers/Bundle/Application/63F61338-338F-4A9B-89ED-B4F2066D6FF5/Catholify.iOS.app/Frameworks/Protobuf.framework/Protobuf' '@rpath/Protobuf.framework/Protobuf' '/System/Library/Frameworks/Protobuf.framework/Protobuf'
    Highlighted by Thread:  0
    
    Backtrace not available
    
    Unknown thread crashed with ARM Thread State (64-bit):
        x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016b7b2070   x3: 0x00000000000000d2
        x4: 0x000000016b7b1c70   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
        x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x75626f746f72502f  x11: 0x77656d6172662e66
       x12: 0x626f746f72502f73  x13: 0x656d6172662e6675  x14: 0x6f72502f6b726f77  x15: 0x0020276675626f74
       x16: 0x0000000000000209  x17: 0x0000000106afd860  x18: 0x0000000000000000  x19: 0x0000000000000000
       x20: 0x000000016b7b1c70  x21: 0x00000000000000d2  x22: 0x000000016b7b2070  x23: 0x0000000000000001
       x24: 0x0000000000000006  x25: 0x0000000106b24000  x26: 0x0000000000000000  x27: 0x0000000106b24000
       x28: 0x0000000000000000   fp: 0x000000016b7b1c40   lr: 0x0000000106b0a914
        sp: 0x000000016b7b1c00   pc: 0x0000000106b032ac cpsr: 0x00000000
       esr: 0x00000000  Address size fault
    
    Binary images description not available
    
    Error Formulating Crash Report:
    Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯
    
    EOF

**Comment by SotoiGhost** [comment]
@edooley Which NuGets do you have installed?

**Comment by edooley** [comment]
@SotoiGhost  Realizing I may have needed to be in #311 as I have the exact same issue as @vincooys. I'll reply there for posterity.

**Comment by SotoiGhost** [comment]
@edooley Yes, please, rollback NuGets version before Feb 24th release. Right now, Firestore doesn't work with most recent versions. We are working on an update to fix this.

**Comment by edooley** [comment]
@SotoiGhost Thanks! That appeared to have worked. I'll keep an eye out for the next update and try it out then.

**Comment by vhugogarcia** [comment]
On the latest version from April, I'm still getting this error. I need to use the latest version for Firebase so I can get the UIWebView warning removed. Any workaround?

**Comment by FIELDPOINT** [comment]
Still getting this error on Crashlytics 8.10.0. I have the following installed. Any ideas?

    <PackageReference Include="Xamarin.Firebase.iOS.Analytics">
      <Version>8.10.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.iOS.Crashlytics">
      <Version>8.10.0</Version>
    </PackageReference>

Tried updating the
