### ISSUE TITLE
Build from App Center failed with sharing violation error

### ISSUE THREAD

**Issue by azuken** [xamarin/GoogleApisForiOSComponents#351]
Hi,

My Xamarin.Forms app does not build anymore on AppCenter (but build in local), with this error : 

Build FAILED.

```
"/Users/runner/runners/2.163.1/work/1/s/XXXX.iOS/XXXX.iOS.csproj" (Rebuild target) (1) ->
(_XamariniOSBuildResourceRestore target) -> 
  /Users/runner/.nuget/packages/xamarin.build.download/0.8.0/buildTransitive/Xamarin.Build.Download.targets(79,3): error : Sharing violation on path /Users/runner/.nuget/packages/xamarin.google.ios.maps/3.5.0/lib/xamarinios10/Google.Maps.dll [/Users/runner/runners/2.163.1/work/1/s/XXXX.iOS/XXXX.iOS.csproj]
/Users/runner/.nuget/packages/xamarin.build.download/0.8.0/buildTransitive/Xamarin.Build.Download.targets(79,3): error :   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <ba70b91736bd40cb990a357097dba9c3>:0  [/Users/runner/runners/2.163.1/work/1/s/XXXX.iOS/XXXX.iOS.csproj]
/Users/runner/.nuget/packages/xamarin.build.download/0.8.0/buildTransitive/Xamarin.Build.Download.targets(79,3): error :   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in <ba70b91736bd40cb990a357097dba9c3>:0  [/Users/runner/runners/2.163.1/work/1/s/XXXX.iOS/XXXX.iOS.csproj]
/Users/runner/.nuget/packages/xamarin.build.download/0.8.0/buildTransitive/Xamarin.Build.Download.targets(79,3): error :   at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare) [/Users/runner/runners/2.163.1/work/1/s/XXXX.iOS/XXXX.iOS.csproj]
/Users/runner/.nuget/packages/xamarin.build.download/0.8.0/buildTransitive/Xamarin.Build.Download.targets(79,3): error :   at Mono.Cecil.ModuleDefinition.GetFileStream (System.String fileName, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00006] in <be358b898f7b4f70a597f036aed20add>:0  [/Users/runner/runners/2.163.1/work/1/s/XXXX.iOS/XXXX.iOS.csproj]
/Users/runner/.nuget/packages/xamarin.build.download/0.8.0/buildTransitive/Xamarin.Build.Download.targets(79,3): error :   at Mono.Cecil.ModuleDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters) [0x00006] in <be358b898f7b4f70a597f036aed20add>:0  [/Users/runner/runners/2.163.1/work/1/s/XXXX.iOS/XXXX.iOS.csproj]
/Users/runner/.nuget/packages/xamarin.build.download/0.8.0/buildTransitive/Xamarin.Build.Download.targets(79,3): error :   at Mono.Cecil.AssemblyDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters) [0x00000] in <be358b898f7b4f70a597f036aed20add>:0  [/Users/runner/runners/2.163.1/work/1/s/XXXX.iOS/XXXX.iOS.csproj]
/Users/runner/.nuget/packages/xamarin.build.download/0.8.0/buildTransitive/Xamarin.Build.Download.targets(79,3): error :   at Mono.Cecil.AssemblyDefinition.Write (System.String fileName) [0x00007] in <be358b898f7b4f70a597f036aed20add>:0  [/Users/runner/runners/2.163.1/work/1/s/XXXX.iOS/XXXX.iOS.csproj]
/Users/runner/.nuget/packages/xamarin.build.download/0.8.0/buildTransitive/Xamarin.Build.Download.targets(79,3): error :   at Xamarin.Build.Download.BaseXamarinBuildResourceRestore.MergeResources (Mono.Cecil.IAssemblyResolver resolver, System.String originalAsmPath, System.String mergedAsmPath, System.String assemblyName, System.Collections.Generic.List`1[T] resourceItems) [0x000fc] in <f9293fcab5a14114beee6a1e59102a2c>:0  [/Users/runner/runners/2.163.1/work/1/s/XXXX.iOS/XXXX.iOS.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:01:00.46
```

I've checked settings and we are actually with latest versions of Xamarin.iOS and Xcode (13.6 & 11.3).

Xamarin.iOS.maps version is 3.5.0

Is there any fix ?

**Comment by johnbmangold** [comment]
Downgrade Xamarin.Build.Download to 0.4.11.

**Comment by azuken** [comment]
OK thank you. Any plan to fix this permanantly, or we have to wait for a Xamarin Build Download update ?

**Comment by azuken** [comment]
Now same problem happen with Visual Sudio build. Downgrade from 0.8.0 to 0.4.11 is not a viable solution. Is there any update ?

**Comment by johnbmangold** [comment]
When did the update go live? As of yesterday morning, it was working for me
using the latest visual studio.

**Comment by azuken** [comment]
It seems it's the .dll download which caused the problem. The file weight was 0b (I've checked this when I found someone on the internet having the same problem), and resolved it when a coworker gave me his working dll file.

**Comment by alexshikov** [comment]
We have the same error using Bitrise. Rebuild usually helps.

**Comment by azuken** [comment]
Rollback to Xamarin.Build.Download 0.4.11 works. But for me it's not a definitive solution.

**Comment by SotoiGhost** [comment]
Hi guys! A very sorry for the inconveniences that this cause. We have released `Xamarin.Build.Download` v0.9.0 that has a potential fix for the error below:

```
Error: Sharing violation on path Foo
```

Please, update and let us know your result.

Best!

**Comment by freever** [comment]
Thanks, it's looking good on our side.

**Comment by johnbmangold** [comment]
`Xamarin.Build.Download` version `0.9.0` with `Xamarin.Google.iOS.Maps` version `3.5.0.1` builds and deploys to a device perfectly fine, but `Xamarin.Build.Download` version `0.9.0` with `Xamarin.Google.iOS.Maps` version `3.7.0` fails with the error:

`Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

This is reproducible every time.

**Comment by Minneth** [comment]
Any news on this?

**Comment by SotoiGhost** [comment]
Hi guys! We have just released `Xamarin.Build.Download` v0.10.0 that fixes

```
Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Please, upgrade, remove bin and obj folders and try again. Thanks guys! And sorry for the inconveniences that this caused.

**Comment by Qythyx** [comment]
I still see the sharing violation error, but only when building in App Center with v0.10.0. When building on my local machine it is fine. In App Center if I downgrade to 0.4.11 then it works. Can this be fixed in a new version of `Xamarin.Build.Download` or is it a problem in App Center?
