### ISSUE TITLE
Could not load file or assembly 'Microsoft.Win32.Registry

### ISSUE THREAD

**Issue by Jared-Aus** [xamarin/GoogleApisForiOSComponents#365]
Xamarin.Firebase.iOS.Auth version 6.2.1.2 does not build successfully from Visual Studio on the PC for my team.  It seems to build ok from VS for Mac however. Going back to 6.2.1.1 solved our build issues.

**Comment by SotoiGhost** [comment]
Hi @Jared-Aus! Xamarin.Build.Download v0.9.0 has been released and contains a possible fix for this issue. Please, update and let us know your results. Best!

**Comment by chrisparkeronline** [comment]
I got the error in 6.2.1, reverting back to 6.0.4.1 fixed the issue for me.

**Comment by pengalo** [comment]
Just got this same error upgrading Xamarin.Google.iOS.MobileAds to v7.53.1. Reverting back to 7.47.0.1 fixed the issue. This is in VS 2019 on Windows.

**Comment by SotoiGhost** [comment]
Hi guys! We have just released `Xamarin.Build.Download` v0.10.0 that fixes this problem on Windows side. Please, upgrade, remove bin and obj folders and try again! Thanks guys and sorry for the inconveniences that this caused.

**Comment by AmirMahdiNassiri** [comment]
@SotoiGhost I have upgraded to Xamarin.Build.Download v0.10.0 but I'm still facing the problem!

**Comment by zoli13** [comment]
>  
> 
> Hi guys! We have just released `Xamarin.Build.Download` v0.10.0 that fixes this problem on Windows side. Please, upgrade, remove bin and obj folders and try again! Thanks guys and sorry for the inconveniences that this caused.

How can I upgrade to `Xamarin.Build.Download` v0.10.0?
I upgraded VS2019 to the latest 16.5.3, but still receive this error:

`2>C:\Users\Myself\.nuget\packages\xamarin.build.download\0.9.0\buildTransitive\Xamarin.Build.Download.targets(52,3): error : Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

**Comment by rayita** [comment]
I got this error with Xamarin.Build.Download v0.8.0, upgrading to v0.10.0 this error desapear but I get one even worst.
For some reason with v0.10.0 some libraris executables (GoogleSymbolUtilities, GoogleTagManager, GoogleUtilities) are been included in ipa file and Spp Store reject the bundle with the following message:

ERROR ITMS-90171_ "Invalid Bunble Structure" - The Binary file 'GoogleUtilities' is not permited. Your app can't contain executables or libraries, other than valid CFBundleExecutabled of supported bundles.

I got one error for each of above mentines libs.

So right now we a stuck, with older version of Xamarin.Build.Download we can't update to newer versions of Google apis components, and with newer version os Xamarin.Build.Download we can update but we cannot upload to appstore.
