### ISSUE TITLE
Can't build app with latest Google Mobile Ads SDK

### ISSUE THREAD

**Issue by tipa** [xamarin/GoogleApisForiOSComponents#372]
After updating Xamarin.Google.iOS.MobileAds to Nuget package 7.53.1, my app fails to build because of these errors:
```
The "XamarinDownloadArchives" task could not be initialized with its input parameters.	
The "AllowUnsecureUrls" parameter is not supported by the "XamarinDownloadArchives" task. Verify the parameter exists on the task, and it is a settable public instance property.	
```
![image](https://user-images.githubusercontent.com/2863198/75243761-c77ba180-57ca-11ea-92d3-034443361823.png)

VS 2019
Xamarin.iOS 13.10.0.17

**Comment by tipa** [comment]
After clearing the bin/obj folders + the whole nuget cache, I am now seeing a different error:
`Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`
![image](https://user-images.githubusercontent.com/2863198/75244803-bf246600-57cc-11ea-895d-e8756cb51448.png)
On Vs for Mac, the project builds however...

**Comment by SotoiGhost** [comment]
@tipa We have just released an update for `Xamarin.Build.Download` nuget that fixes this issue. Please, update, remove your obj and bin folders and try again. Hope this helps you! Best!

**Comment by AmirMahdiNassiri** [comment]
@SotoiGhost Can you please let us know which version of Xamarin.Build.Download you are referring to? I am using the latest version 0.10 but still experiencing the issue.

**Comment by Minneth** [comment]
I can second the above - I'm also getting the same issue after updating to the new version 0.10. I've obviously cleared obj/bin and restarted the IDE.

**Comment by kaanakyalcin** [comment]
any progress? same issue here
