### ISSUE TITLE
Object reference not set to an instance of an object in task XamarinDownloadArchives

### ISSUE THREAD

**Issue by hichaam2** [xamarin/GoogleApisForiOSComponents#55]
Hello,

Using visual studio 2017 RC, the build is not successfull, it throws an exception in task XamarinDownloadArchives, I tried the AdMobSample project without any modification, and below the error in build log:

`5>Target "_XamarinBuildDownloadCore" in file "C:\Users\Hicham\Documents\Visual Studio 2017\Projects\GoogleApisForiOSComponents\Firebase.AdMob\samples\AdMobSample\packages\Xamarin.Build.Download.0.2.2\build\Xamarin.Build.Download.targets" from project "C:\Users\Hicham\Documents\Visual Studio 2017\Projects\GoogleApisForiOSComponents\Firebase.AdMob\samples\AdMobSample\AdMobSample\AdMobSample.csproj" (target "_XamarinBuildDownload" depends on it):
5>Task "Error" skipped, due to false condition; ('$(XamarinBuildDownloadDir)'=='') was evaluated as ('C:\Users\Hicham\Documents\Visual Studio 2017\Projects\GoogleApisForiOSComponents\Firebase.AdMob\samples\AdMobSample\packages\Xamarin.Build.Download.0.2.2\build\..\..\.xbcache\'=='').
5>Using "XamarinDownloadArchives" task from assembly "C:\Users\Hicham\Documents\Visual Studio 2017\Projects\GoogleApisForiOSComponents\Firebase.AdMob\samples\AdMobSample\packages\Xamarin.Build.Download.0.2.2\build\Xamarin.Build.Download.dll".
5>Task "XamarinDownloadArchives"
5>  Task Parameter:
5>      Archives=
5>          FInstncID-1.0.8
5>                  Kind=Tgz
5>                  Url=https://www.gstatic.com/cpdc/18da95d517c54d0f/FirebaseInstanceID-1.0.8.tar.gz
5>          FCr-3.4.5
5>                  Kind=Tgz
5>                  Url=https://dl.google.com/dl/cpdc/23ffbc519fdeb8d5/FirebaseCore-3.4.5.tar.gz
5>          GIntrchngU-1.2.2
5>                  Kind=Tgz
5>                  Url=https://dl.google.com/dl/cpdc/1a7f7ba905b2c029/GoogleInterchangeUtilities-1.2.2.tar.gz
5>          FAnlytcs-3.6.0
5>                  Kind=Tgz
5>                  Url=https://dl.google.com/dl/cpdc/b8b4edfd2453a212/FirebaseAnalytics-3.6.0.tar.gz
5>          GSymblU-1.1.2
5>                  Kind=Tgz
5>                  Url=https://dl.google.com/dl/cpdc/7ecdffda6fbef4af/GoogleSymbolUtilities-1.1.2.tar.gz
5>          Gmbladssdk-7.15.0
5>                  Kind=Tgz
5>                  Url=https://dl.google.com/dl/cpdc/7d719f8d49d44418-Google-Mobile-Ads-SDK-7.15.0.tar.gz
5>  Task Parameter:DestinationBase=C:\Users\Hicham\Documents\Visual Studio 2017\Projects\GoogleApisForiOSComponents\Firebase.AdMob\samples\AdMobSample\packages\Xamarin.Build.Download.0.2.2\build\..\..\.xbcache\
5>    Downloading https://www.gstatic.com/cpdc/18da95d517c54d0f/FirebaseInstanceID-1.0.8.tar.gz to C:\Users\Hicham\AppData\Local\XamarinBuildDownloadCache\FInstncID-1.0.8.tgz
5>  	(2368/-1b), total 0,0%
5>  	(1364294/1364294b), total 100,0%
5>    Downloading Complete
5>C:\Users\Hicham\Documents\Visual Studio 2017\Projects\GoogleApisForiOSComponents\Firebase.AdMob\samples\AdMobSample\packages\Xamarin.Build.Download.0.2.2\build\Xamarin.Build.Download.targets(25,3): error : Object reference not set to an instance of an object.
5>Done executing task "XamarinDownloadArchives" -- FAILED.
5>Done building target "_XamarinBuildDownloadCore" in project "AdMobSample.csproj" -- FAILED.
5>
5>Build FAILED.`

**Comment by brenkehoe** [comment]
Same problem here:

1>Target "_XamarinBuildDownloadCore: (TargetId:73)" in file "C:\Users\xxxx\documents\visual studio 2017\Projects\ninetiesboy\packages\Xamarin.Build.Download.0.4.1\build\Xamarin.Build.Download.targets" from project "C:\Users\bren\documents\visual studio 2017\Projects\ninetiesboy\ninetiesboy\ninetiesboy.csproj" (target "_XamarinBuildDownload" depends on it):
1>Using "XamarinDownloadArchives" task from assembly "C:\Users\xxxx\documents\visual studio 2017\Projects\ninetiesboy\packages\Xamarin.Build.Download.0.4.1\build\Xamarin.Build.Download.dll".
1>Task "XamarinDownloadArchives" (TaskId:32)
1>  Task Parameter:
1>      Archives=
1>          FCr-3.4.4
1>                  Kind=Tgz
1>                  Url=https://dl.google.com/dl/cpdc/45f8dcf1d763c6c2/FirebaseCore-3.4.4.tar.gz
1>          FInstncID-1.0.8
1>                  Kind=Tgz
1>                  Url=https://www.gstatic.com/cpdc/18da95d517c54d0f/FirebaseInstanceID-1.0.8.tar.gz
1>          FAnlytcs-3.5.1
1>                  Kind=Tgz
1>                  Url=https://dl.google.com/dl/cpdc/54af7874047de62c/FirebaseAnalytics-3.5.1.tar.gz
1>          GSymblU-1.1.2
1>                  Kind=Tgz
1>                  Url=https://dl.google.com/dl/cpdc/7ecdffda6fbef4af/GoogleSymbolUtilities-1.1.2.tar.gz
1>          GIntrchngU-1.2.2
1>                  Kind=Tgz
1>                  Url=https://dl.google.com/dl/cpdc/1a7f7ba905b2c029/GoogleInterchangeUtilities-1.2.2.tar.gz
1>          FAth-3.0.6
1>                  Kind=Tgz
1>                  Url=https://dl.google.com/dl/cpdc/c3b1d3ce85311140/FirebaseAuth-3.0.6.tar.gz
1>          FDtbs-3.1.0
1>                  Kind=Tgz
1>                  Url=https://dl.google.com/dl/cpdc/1e3900e14edb8ce1/FirebaseDatabase-3.1.0.tar.gz (TaskId:32)
1>  Task Parameter:DestinationBase=C:\Users\xxxx\AppData\Local\XamarinBuildDownloadCache\ (TaskId:32)
1>  Task Parameter:CacheDirectory=C:\Users\xxxx\AppData\Local\XamarinBuildDownloadCache\ (TaskId:32)
1>C:\Users\xxxx\documents\visual studio 2017\Projects\ninetiesboy\packages\Xamarin.Build.Download.0.4.1\build\Xamarin.Build.Download.targets(38,3): error : Object reference not set to an instance of an object.
1>Done executing task "XamarinDownloadArchives" -- FAILED. (TaskId:32)
1>Done building target "_XamarinBuildDownloadCore" in project "ninetiesboy.csproj" -- FAILED.: (TargetId:73)



Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26020.0 D15REL
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Xamarin   4.3.0.458 (e738933)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   7.1.0.13 (72366f7)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   10.4.0.33 (d93ae7e)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by hardcodet** [comment]
Same here trying to leverage the Maps APIs:

\packages\Xamarin.Build.Download.0.4.1\build\Xamarin.Build.Download.targets(38,3): error : Object reference not set to an instance of an object.

This is a showstopper issue - I can't even open my Android/iOS projects in VS2015 anymore...
Since this component seems to be downloading stuff, is there any way to hack around this (e.g. by putting required binaries anywhere?)

**Comment by belandsoft** [comment]
I have this problem too on VS2017 RC and latest beta xamarin

**Comment by bholmes** [comment]
We are working on fixes for VS 2017.  Can you please try updating Xamarin Build Download to [0.4.3-beta1](https://www.nuget.org/packages/Xamarin.Build.Download/0.4.3-beta1)?  

Please report your findings as we attempt to correct this issue.

**Comment by belandsoft** [comment]
Using 0.4.3-beta1 seems to be working good

**Comment by bholmes** [comment]
beta6 is out there now.  Hope to release soon, maybe even today.

**Comment by hichaam2** [comment]
Solved with beta6

**Comment by ahmadalgarni** [comment]
I am still facing the same problem One year later, I have tried all possible versions of Xamarin Build Download, but still getting  Object reference not set to an instance of an object,

I am delayed two days in submitting the project because of this issue,

Can Anyone help please ?

**Comment by HassanJawed** [comment]
I am facing this issue again. Please open the issue again

**Comment by santiagohdzb** [comment]
It's happening again

```
...\Xamarin.Build.Download.0.4.2\build\Xamarin.Build.Download.targets(38,3): error : Object reference not set to an instance of an object.
```

![imagen](https://user-images.githubusercontent.com/8533075/54224647-8dcd6000-44bf-11e9-883b-1b3e60732664.png)
